server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index html/index.html;

    location = /health {
        access_log off;
        default_type text/plain;

        return 200 "OK";
    }

    location / {
        try_files $uri $uri/ /html/index.html;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(env|git|md|yml|yaml|json|lock)$ {
        deny all;
    }
}